name: Run test with ci/cd

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  run_api_automation:
    runs-on: ubuntu-latest #mesin untuk jalanin
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run test with pytest
        run: pytest test/ -v
        env:
          WEBHOOK_SLACK: ${{ secrets.WEBHOOK_SLACK }}
          QASE_IO_TOKEN: ${{ secrets.QASE_IO_TOKEN }}

      - name: Send Report Slack
        run: python setting/slack_notif.py
        env:
          WEBHOOK_SLACK: ${{ secrets.WEBHOOK_SLACK }}

